image: node:10

cache:
  paths:
    - client/node_modules

before_script:
  - cd client
  - npm install

pages:
  stage: deploy
  script:
    - CI=true npm build
    - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - mv build ../public
  artifacts:
    paths:
      - public
  # only:
  # - master
