image: alpine:latest

pages:
  stage: deploy
  script:
    - find client -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - client/build
  # only:
  # - master
